version: '3'

services:
    mysql:
      image: mysql:latest
      container_name: java-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: library
        MYSQL_USER: nesterlom
        MYSQL_PASSWORD: DBilyha2280!

      volumes:
        - my-db:/var/lib/mysql

    backend:
      build: ./
      container_name: java-backend
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library
      depends_on:
        - mysql

volumes:
  my-db: