version: '3'

services:
    mysql:
      image: mysql:latest
      container_name: java-db
      environment:
        MYSQL_DATABASE: 'library'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'DBilyha2280!'
        MYSQL_ROOT_PASSWORD: 'password'

    backend:
      build: ./
      container_name: java-backend
      ports:
        - "8080:8080"